"""add data_sources.status

Revision ID: 0d8003eda947
Revises: 77b3c98595c7
Create Date: 2026-07-02 22:50:53.083978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d8003eda947'
down_revision: Union[str, None] = '77b3c98595c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('status', sa.String(), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'status')
    # ### end Alembic commands ###
