"""create object_factories table

Revision ID: 584948feb36e
Revises: 459661c587fc
Create Date: 2026-06-19 20:15:20.257867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584948feb36e'
down_revision: Union[str, None] = '459661c587fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_factories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_name', sa.String(), nullable=False),
    sa.Column('object_type_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_name'], ['catalogs.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_name', 'object_type_id', name='uq_object_factories_catalog_type')
    )
    op.create_index(op.f('ix_object_factories_catalog_name'), 'object_factories', ['catalog_name'], unique=False)
    op.create_index(op.f('ix_object_factories_object_type_id'), 'object_factories', ['object_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_object_factories_object_type_id'), table_name='object_factories')
    op.drop_index(op.f('ix_object_factories_catalog_name'), table_name='object_factories')
    op.drop_table('object_factories')
    # ### end Alembic commands ###
