"""flex_modules

Revision ID: 77b3c98595c7
Revises: f52a069f4325
Create Date: 2026-06-22 20:40:55.798743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b3c98595c7'
down_revision: Union[str, None] = 'f52a069f4325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flex_modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_name', sa.String(), nullable=False),
    sa.Column('source_text', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_name'], ['catalogs.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_name', name='uq_flex_modules_catalog')
    )
    op.create_index(op.f('ix_flex_modules_catalog_name'), 'flex_modules', ['catalog_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flex_modules_catalog_name'), table_name='flex_modules')
    op.drop_table('flex_modules')
    # ### end Alembic commands ###
