"""add status + last_error to object_factories

Revision ID: cbc8eba7b694
Revises: ffff32b963ed
Create Date: 2026-06-21 19:19:58.517117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc8eba7b694'
down_revision: Union[str, None] = 'ffff32b963ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_factories', sa.Column('status', sa.String(), server_default='ok', nullable=False))
    op.add_column('object_factories', sa.Column('last_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object_factories', 'last_error')
    op.drop_column('object_factories', 'status')
    # ### end Alembic commands ###
