"""add column-spec to object_factories

Revision ID: f10483ccd160
Revises: 584948feb36e
Create Date: 2026-06-19 20:30:10.354245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10483ccd160'
down_revision: Union[str, None] = '584948feb36e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_factories', sa.Column('use_all_columns', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('object_factories', sa.Column('column_spec', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object_factories', 'column_spec')
    op.drop_column('object_factories', 'use_all_columns')
    # ### end Alembic commands ###
