"""object_type_traits + factory trait_config

Revision ID: f52a069f4325
Revises: cbc8eba7b694
Create Date: 2026-06-21 20:11:20.689572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52a069f4325'
down_revision: Union[str, None] = 'cbc8eba7b694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_type_traits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_type_id', sa.UUID(), nullable=False),
    sa.Column('trait_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_type_id'], ['object_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_type_id', 'trait_name', name='uq_object_type_traits_pair')
    )
    op.create_index(op.f('ix_object_type_traits_object_type_id'), 'object_type_traits', ['object_type_id'], unique=False)
    op.add_column('object_factories', sa.Column('trait_config', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object_factories', 'trait_config')
    op.drop_index(op.f('ix_object_type_traits_object_type_id'), table_name='object_type_traits')
    op.drop_table('object_type_traits')
    # ### end Alembic commands ###
