import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";

import {
  createObjectFactory,
  listObjectFactories,
  type ObjectFactory,
} from "@/api/objectFactories";
import { listObjectTypes, type ObjectType } from "@/api/objectTypes";
import { ApiError } from "@/api/client";

/**
 * Lists object factories that read from a specific data source. Shown on the
 * Data Source detail page. Lets you attach a new object type (each click
 * creates a new factory on this source) via a picker of types not yet
 * attached here.
 */
export function DataSourceFactoriesPanel({ dataSourceId }: { dataSourceId: string }) {
  const qc = useQueryClient();
  const factories = useQuery({
    queryKey: ["object-factories", { data_source_id: dataSourceId }],
    queryFn: () => listObjectFactories({ data_source_id: dataSourceId }),
  });
  const allTypes = useQuery({
    queryKey: ["object-types", { search: "" }],
    queryFn: () => listObjectTypes(),
  });

  const attachedIds = new Set(factories.data?.map((f) => f.object_type_id) ?? []);
  const candidates = (allTypes.data ?? []).filter((t) => !attachedIds.has(t.id));

  return (
    <Panel
      heading="Produces objects"
      pickerLabel="Object type"
      candidates={candidates}
      candidateLabel={(t: ObjectType) => t.name}
      candidateValue={(t: ObjectType) => t.id}
      onAttach={async (object_type_id) => {
        await createObjectFactory({
          data_source_id: dataSourceId,
          object_type_id,
          description: "",
        });
        await qc.invalidateQueries({ queryKey: ["object-factories"] });
      }}
      emptyText="This data source isn't producing any object types yet."
      loading={factories.isLoading || allTypes.isLoading}
      factories={factories.data ?? []}
      rowLabel={(f) => f.object_type_name ?? f.object_type_id}
    />
  );
}

/**
 * Lists object factories filtered by an object type. Used on the Object Type
 * detail page. Read-only — you manage factories from the data source side.
 * The row label shows the full `catalog.schema.table` path so the user can
 * trace where each instance comes from.
 */
export function ObjectTypeFactoriesPanel({ typeId }: { typeId: string }) {
  const factories = useQuery({
    queryKey: ["object-factories", { object_type_id: typeId }],
    queryFn: () => listObjectFactories({ object_type_id: typeId }),
  });

  return (
    <Panel
      heading="Generated by data sources"
      pickerLabel="Data source"
      candidates={[]}
      candidateLabel={() => ""}
      candidateValue={() => ""}
      onAttach={async () => {
        /* picker is suppressed; this is never called */
      }}
      emptyText="No data sources are producing this object type yet. Attach this type from a data source's page."
      loading={factories.isLoading}
      factories={factories.data ?? []}
      rowLabel={(f) => f.data_source_path ?? f.data_source_id}
      readOnly
    />
  );
}

function ColumnsBadge({ factory }: { factory: ObjectFactory }) {
  if (factory.use_all_columns) {
    return (
      <span
        className="rounded bg-zinc-100 px-1.5 py-0.5 text-[10px] font-medium uppercase tracking-wide text-zinc-600"
        data-testid={`columns-badge-${factory.id}`}
      >
        all cols
      </span>
    );
  }
  const count = factory.column_spec.length;
  return (
    <span
      className="rounded bg-emerald-100 px-1.5 py-0.5 text-[10px] font-medium uppercase tracking-wide text-emerald-800"
      data-testid={`columns-badge-${factory.id}`}
    >
      {count} col{count === 1 ? "" : "s"}
    </span>
  );
}

interface PanelProps<TCandidate> {
  heading: string;
  pickerLabel: string;
  candidates: TCandidate[];
  candidateLabel: (c: TCandidate) => string;
  candidateValue: (c: TCandidate) => string;
  onAttach: (value: string) => Promise<void>;
  loading: boolean;
  factories: ObjectFactory[];
  rowLabel: (f: ObjectFactory) => string;
  emptyText: string;
  /** When true, no add-button / picker is shown. */
  readOnly?: boolean;
}

function Panel<TCandidate>({
  heading,
  pickerLabel,
  candidates,
  candidateLabel,
  candidateValue,
  onAttach,
  loading,
  factories,
  rowLabel,
  emptyText,
  readOnly = false,
}: PanelProps<TCandidate>) {
  const [picking, setPicking] = useState(false);
  const [selected, setSelected] = useState("");
  const [error, setError] = useState<string | null>(null);

  const attach = useMutation({
    mutationFn: () => onAttach(selected),
    onSuccess: () => {
      setSelected("");
      setError(null);
      setPicking(false);
    },
    onError: (err: unknown) => {
      if (err instanceof ApiError) {
        const body = (err.body ?? {}) as { error?: string; details?: unknown };
        if (body.details) {
          setError(
            typeof body.details === "string"
              ? body.details
              : JSON.stringify(body.details),
          );
          return;
        }
        setError(`${body.error ?? "Request failed"} (HTTP ${err.status})`);
        return;
      }
      setError((err as Error).message);
    },
  });

  return (
    <section data-testid="object-factories-panel">
      <div className="mb-2 flex items-center justify-between">
        <h2 className="text-xs font-medium uppercase tracking-wide text-zinc-500">
          {heading}
        </h2>
        {!readOnly && !picking && (
          <button
            type="button"
            onClick={() => {
              setPicking(true);
              setError(null);
            }}
            disabled={loading}
            className="rounded border border-zinc-200 bg-white px-2.5 py-1 text-xs font-medium text-zinc-700 hover:bg-zinc-50 disabled:cursor-not-allowed disabled:opacity-50"
            data-testid="attach-button"
          >
            + Add {pickerLabel.toLowerCase()}
          </button>
        )}
      </div>

      {!readOnly && picking && (
        <form
          className="mb-3 space-y-2 rounded border border-zinc-200 bg-zinc-50 p-3"
          data-testid="attach-form"
          onSubmit={(e) => {
            e.preventDefault();
            if (!selected) {
              setError(`Pick a ${pickerLabel.toLowerCase()} first.`);
              return;
            }
            attach.mutate();
          }}
        >
          <label
            htmlFor="attach-select"
            className="mb-1 block text-xs font-medium uppercase tracking-wide text-zinc-500"
          >
            {pickerLabel}
          </label>
          {candidates.length === 0 ? (
            <p className="text-sm text-zinc-500" data-testid="no-candidates">
              No {pickerLabel.toLowerCase()}s available to attach.
            </p>
          ) : (
            <select
              id="attach-select"
              value={selected}
              onChange={(e) => setSelected(e.target.value)}
              className="block w-full rounded border border-zinc-200 bg-white px-3 py-1.5 text-sm focus:border-zinc-400 focus:outline-none focus:ring-1 focus:ring-zinc-400"
              data-testid="attach-select"
            >
              <option value="">— pick one —</option>
              {candidates.map((c) => (
                <option key={candidateValue(c)} value={candidateValue(c)}>
                  {candidateLabel(c)}
                </option>
              ))}
            </select>
          )}
          {error && (
            <div
              className="rounded border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-800"
              data-testid="attach-error"
            >
              {error}
            </div>
          )}
          <div className="flex items-center gap-2">
            <button
              type="submit"
              disabled={attach.isPending || candidates.length === 0}
              className="rounded bg-zinc-900 px-3 py-1.5 text-sm font-medium text-white hover:bg-zinc-800 disabled:cursor-not-allowed disabled:opacity-50"
              data-testid="attach-submit"
            >
              {attach.isPending ? "Attaching..." : "Attach"}
            </button>
            <button
              type="button"
              onClick={() => {
                setPicking(false);
                setSelected("");
                setError(null);
              }}
              className="rounded border border-zinc-200 bg-white px-3 py-1.5 text-sm font-medium text-zinc-700 hover:bg-zinc-50"
            >
              Cancel
            </button>
          </div>
        </form>
      )}

      {loading ? (
        <p className="text-sm text-zinc-500">Loading...</p>
      ) : factories.length === 0 ? (
        <p
          className="rounded border border-dashed border-zinc-200 p-4 text-sm text-zinc-500"
          data-testid="factories-empty"
        >
          {emptyText}
        </p>
      ) : (
        <ul
          className="divide-y divide-zinc-100 rounded border border-zinc-200 bg-white"
          data-testid="factories-list"
        >
          {factories.map((f) => (
            <li key={f.id}>
              <Link
                to={`/object-factories/${f.id}`}
                className="block px-4 py-2.5 hover:bg-zinc-50"
                data-testid={`factory-row-${f.id}`}
              >
                <div className="flex items-baseline justify-between gap-4">
                  <span className="font-medium text-zinc-900">
                    {f.status === "broken" && (
                      <span
                        className="mr-1.5 inline-block size-1.5 rounded-full bg-red-500 align-middle"
                        title={f.last_error ?? "broken"}
                        data-testid={`factory-broken-dot-${f.id}`}
                      />
                    )}
                    {rowLabel(f)}
                  </span>
                  <ColumnsBadge factory={f} />
                </div>
                {f.description && (
                  <p className="mt-0.5 line-clamp-1 text-sm text-zinc-600">
                    {f.description}
                  </p>
                )}
              </Link>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}
